[window]
#dimensions = { columns = 150, lines = 40 }
dimensions = { columns = 220, lines = 60 }
padding = { x = 3, y = 3 }
dynamic_padding = true
opacity = 0.9
decorations = "None"

[font]
size = 16.0
